      var items = [
      // ==================== CONSUMABLES (PHARMACIST) ====================
      // Table A
      { name: "Potion of Healing", price: 50, rarity: "common", shops: ["pharmacist", "general"], loot: ["civilian", "guard", "military", "space"], category: "consumable" },
      { name: "Spell Scroll (Cantrip)", price: 25, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Potion of Climbing", price: 75, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Spell Scroll (1st Level)", price: 75, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Spell Scroll (2nd Level)", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Potion of Greater Healing", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Bag of Holding", price: 500, rarity: "uncommon", shops: ["general", "pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Driftglobe", price: 200, rarity: "uncommon", shops: ["general", "pharmacist"], loot: ["military", "space"], category: "wondrous" },

      // Table B
      { name: "Potion of Fire Breath", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Potion of Resistance", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Ammunition, +1 (each)", price: 25, rarity: "uncommon", shops: ["firearms"], loot: ["military", "space"], category: "ammo" },
      { name: "Potion of Animal Friendship", price: 100, rarity: "uncommon", shops: ["pharmacist"], loot: ["civilian", "guard"], category: "consumable" },
      { name: "Potion of Hill Giant Strength", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Potion of Growth", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Potion of Water Breathing", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Spell Scroll (3rd Level)", price: 300, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Keoghtom's Ointment", price: 200, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Oil of Slipperiness", price: 200, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Dust of Disappearance", price: 200, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Dust of Dryness", price: 150, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Dust of Sneezing and Choking", price: 200, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Elemental Gem", price: 300, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Philter of Love", price: 100, rarity: "uncommon", shops: ["pharmacist"], loot: ["civilian", "guard"], category: "consumable" },
      { name: "Alchemy Jug", price: 200, rarity: "uncommon", shops: ["pharmacist", "general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Cap of Water Breathing", price: 200, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Cloak of the Manta Ray", price: 200, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Goggles of Night", price: 200, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Helm of Comprehending Languages", price: 200, rarity: "uncommon", shops: ["cybernetics"], loot: ["civilian", "guard", "military"], category: "wondrous" },
      { name: "Immovable Rod", price: 200, rarity: "uncommon", shops: ["general", "cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Lantern of Revealing", price: 200, rarity: "uncommon", shops: ["general"], loot: ["guard", "military", "space"], category: "wondrous" },
      { name: "Mariner's Armor", price: 300, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Mithral Armor", price: 400, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Potion of Poison", price: 100, rarity: "uncommon", shops: ["pharmacist"], loot: ["guard", "military", "space"], category: "consumable" },
      { name: "Ring of Swimming", price: 200, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Robe of Useful Items", price: 200, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Rope of Climbing", price: 200, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Saddle of the Cavalier", price: 200, rarity: "uncommon", shops: ["general"], loot: ["military"], category: "wondrous" },
      { name: "Wand of Magic Detection", price: 200, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Wand of Secrets", price: 200, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },

      // Table C
      { name: "Potion of Superior Healing", price: 450, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Spell Scroll (4th Level)", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Ammunition, +2 (each)", price: 100, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "ammo" },
      { name: "Potion of Clairvoyance", price: 400, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Potion of Diminution", price: 400, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Potion of Gaseous Form", price: 400, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Potion of Frost Giant Strength", price: 450, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Stone Giant Strength", price: 450, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Heroism", price: 400, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Potion of Invulnerability", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Mind Reading", price: 400, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Spell Scroll (5th Level)", price: 750, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Elixir of Health", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Oil of Etherealness", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Fire Giant Strength", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Quaal's Feather Token", price: 400, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Scroll of Protection", price: 400, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Bag of Beans", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Bead of Force", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "consumable" },
      { name: "Chime of Opening", price: 500, rarity: "rare", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Decanter of Endless Water", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Eyes of Minute Seeing", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Folding Boat", price: 500, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Heward's Handy Haversack", price: 500, rarity: "rare", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Horseshoes of Speed", price: 500, rarity: "rare", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Necklace of Fireballs", price: 500, rarity: "rare", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Periapt of Health", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Sending Stones", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },

      // Table D
      { name: "Potion of Supreme Healing", price: 1350, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Invisibility", price: 1000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Speed", price: 1000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Spell Scroll (6th Level)", price: 1500, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Spell Scroll (7th Level)", price: 2500, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Ammunition, +3 (each)", price: 500, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "ammo" },
      { name: "Oil of Sharpness", price: 1000, rarity: "veryRare", shops: ["pharmacist", "firearms"], loot: ["space"], category: "consumable" },
      { name: "Potion of Flying", price: 1000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Cloud Giant Strength", price: 1000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Longevity", price: 1500, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Vitality", price: 1000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Spell Scroll (8th Level)", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Horseshoes of a Zephyr", price: 1500, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Nolzur's Marvelous Pigments", price: 1500, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Bag of Devouring", price: 1000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Portable Hole", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },

      // Table E
      { name: "Spell Scroll (9th Level)", price: 10000, rarity: "legendary", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Potion of Storm Giant Strength", price: 2000, rarity: "legendary", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Universal Solvent", price: 1500, rarity: "legendary", shops: ["pharmacist"], loot: ["space"], category: "consumable" },
      { name: "Arrow of Slaying", price: 2000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "ammo" },
      { name: "Sovereign Glue", price: 1500, rarity: "legendary", shops: ["pharmacist"], loot: ["space"], category: "consumable" },

      // ==================== TABLE F (Uncommon Permanent) ====================
      { name: "Weapon, +1", price: 500, rarity: "uncommon", shops: ["firearms"], loot: ["military", "space"], category: "weapon" },
      { name: "Shield, +1", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Sentinel Shield", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Amulet of Proof Against Detection and Location", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Boots of Elvenkind", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Boots of Striding and Springing", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Bracers of Archery", price: 500, rarity: "uncommon", shops: ["cybernetics", "firearms"], loot: ["military", "space"], category: "wondrous" },
      { name: "Brooch of Shielding", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Broom of Flying", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Cloak of Elvenkind", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Cloak of Protection", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Gauntlets of Ogre Power", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Hat of Disguise", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Javelin of Lightning", price: 500, rarity: "uncommon", shops: ["firearms"], loot: ["military", "space"], category: "weapon" },
      { name: "Pearl of Power", price: 500, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Rod of the Pact Keeper, +1", price: 500, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Slippers of Spider Climbing", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Staff of the Adder", price: 500, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "weapon" },
      { name: "Staff of the Python", price: 500, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "weapon" },
      { name: "Sword of Vengeance", price: 500, rarity: "uncommon", shops: ["firearms"], loot: ["military", "space"], category: "weapon" },
      { name: "Trident of Fish Command", price: 500, rarity: "uncommon", shops: ["firearms"], loot: ["military", "space"], category: "weapon" },
      { name: "Wand of Magic Missiles", price: 500, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Wand of the War Mage, +1", price: 500, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Wand of Web", price: 500, rarity: "uncommon", shops: ["pharmacist"], loot: ["military", "space"], category: "wondrous" },
      { name: "Weapon of Warning", price: 500, rarity: "uncommon", shops: ["firearms"], loot: ["military", "space"], category: "weapon" },
      { name: "Adamantine Armor (Chain Mail)", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Adamantine Armor (Chain Shirt)", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Adamantine Armor (Scale Mail)", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Bag of Tricks (Gray)", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Bag of Tricks (Rust)", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Bag of Tricks (Tan)", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Boots of the Winterlands", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Circlet of Blasting", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Deck of Illusions", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Eversmoking Bottle", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Eyes of Charming", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Eyes of the Eagle", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Silver Raven)", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Gem of Brightness", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Gloves of Missile Snaring", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Gloves of Swimming and Climbing", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Gloves of Thievery", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Headband of Intellect", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Helm of Telepathy", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Instrument of the Bards (Doss Lute)", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Instrument of the Bards (Fochlucan Bandore)", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Instrument of the Bards (Mac-Fuirmidh Cittern)", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Medallion of Thoughts", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Necklace of Adaptation", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Periapt of Wound Closure", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Pipes of Haunting", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Pipes of the Sewers", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Ring of Jumping", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Ring of Mind Shielding", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Ring of Warmth", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Ring of Water Walking", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },
      { name: "Quiver of Ehlonna", price: 500, rarity: "uncommon", shops: ["firearms"], loot: ["military", "space"], category: "wondrous" },
      { name: "Stone of Good Luck", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Wind Fan", price: 500, rarity: "uncommon", shops: ["general"], loot: ["military", "space"], category: "wondrous" },
      { name: "Winged Boots", price: 500, rarity: "uncommon", shops: ["cybernetics"], loot: ["military", "space"], category: "wondrous" },

      // ==================== TABLE G (Rare) ====================
      { name: "Weapon, +2", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Figurine of Wondrous Power (Bronze Griffon)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Ebony Fly)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Golden Lions)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Ivory Goats)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Marble Elephant)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Onyx Dog)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Serpentine Owl)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Adamantine Armor (Breastplate)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Adamantine Armor (Splint)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Amulet of Health", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Armor of Vulnerability", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Arrow-Catching Shield", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Belt of Dwarvenkind", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Belt of Hill Giant Strength", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Berserker Axe", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Boots of Levitation", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Boots of Speed", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Bowl of Commanding Water Elementals", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Bracers of Defense", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Brazier of Commanding Fire Elementals", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Cape of the Mountebank", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Censer of Controlling Air Elementals", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +1 Chain Mail", price: 1500, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Chain Mail)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Chain Shirt)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +1 Chain Shirt", price: 1500, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Cloak of Displacement", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Cloak of the Bat", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Cube of Force", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Daern's Instant Fortress", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Dagger of Venom", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Dimensional Shackles", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Dragon Slayer", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Elven Chain", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Flame Tongue", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Gem of Seeing", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Giant Slayer", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Glamoured Studded Leather", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Helm of Teleportation", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Horn of Blasting", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Horn of Valhalla (Silver)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Horn of Valhalla (Brass)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Instrument of the Bards (Canaith Mandolin)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Instrument of the Bards (Cli Lyre)", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Awareness)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Protection)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Reserve)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Sustenance)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Iron Bands of Bilarro", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +1 Leather", price: 1500, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Leather)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Mace of Disruption", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Mace of Smiting", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Mace of Terror", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Mantle of Spell Resistance", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Necklace of Prayer Beads", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Periapt of Proof Against Poison", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Animal Influence", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Evasion", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Feather Falling", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Free Action", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Protection", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Resistance", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Spell Storing", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of the Ram", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of X-ray Vision", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Robe of Eyes", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Rod of Rulership", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Rod of the Pact Keeper, +2", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Rope of Entanglement", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +1 Scale Mail", price: 1500, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Scale Mail)", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Shield, +2", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Shield of Missile Attraction", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Staff of Charming", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of Healing", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of Swarming Insects", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of the Woodlands", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of Withering", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Stone of Controlling Earth Elementals", price: 2000, rarity: "rare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Sun Blade", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Sword of Life Stealing", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Sword of Wounding", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Tentacle Rod", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Vicious Weapon", price: 2000, rarity: "rare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Wand of Binding", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of Enemy Detection", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of Fear", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of Fireballs", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of Lightning Bolts", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of Paralysis", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of the War Mage, +2", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of Wonder", price: 2000, rarity: "rare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wings of Flying", price: 2000, rarity: "rare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },

      // ==================== TABLE H (Very Rare) ====================
      { name: "Weapon, +3", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Amulet of the Planes", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Carpet of Flying", price: 5000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Crystal Ball", price: 5000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Regeneration", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Shooting Stars", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Telekinesis", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Robe of Scintillating Colors", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Robe of Stars", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Rod of Absorption", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Rod of Alertness", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Rod of Security", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Rod of the Pact Keeper, +3", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Scimitar of Speed", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Shield, +3", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Staff of Fire", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of Frost", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of Power", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of Striking", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Staff of Thunder and Lightning", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "weapon" },
      { name: "Sword of Sharpness", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Wand of Polymorph", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Wand of the War Mage, +3", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Adamantine Armor (Half Plate)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Adamantine Armor (Plate)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Animated Shield", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Belt of Fire Giant Strength", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Belt of Frost Giant Strength", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Belt of Stone Giant Strength", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +1 Breastplate", price: 4000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Breastplate)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Candle of Invocation", price: 5000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +2 Chain Mail", price: 4000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +2 Chain Shirt", price: 4000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Cloak of Arachnida", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Dancing Sword", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Demon Armor", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Dragon Scale Mail", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Dwarven Plate", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Dwarven Thrower", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Efreeti Bottle", price: 5000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Figurine of Wondrous Power (Obsidian Steed)", price: 5000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Frost Brand", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Helm of Brilliance", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Horn of Valhalla (Bronze)", price: 5000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Instrument of the Bards (Anstruth Harp)", price: 5000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Absorption)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Agility)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Fortitude)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Insight)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Intellect)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Leadership)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Strength)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +2 Leather", price: 4000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Manual of Bodily Health", price: 10000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Manual of Gainful Exercise", price: 10000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Manual of Golems", price: 10000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Manual of Quickness of Action", price: 10000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Mirror of Life Trapping", price: 5000, rarity: "veryRare", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Nine Lives Stealer", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Oathbow", price: 5000, rarity: "veryRare", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Armor, +2 Scale Mail", price: 4000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Spellguard Shield", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +1 Splint", price: 4000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Splint)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +1 Studded Leather", price: 4000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Studded Leather)", price: 5000, rarity: "veryRare", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Tome of Clear Thought", price: 10000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Tome of Leadership and Influence", price: 10000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Tome of Understanding", price: 10000, rarity: "veryRare", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },

      // ==================== TABLE I (Legendary) ====================
      { name: "Defender", price: 25000, rarity: "legendary", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Hammer of Thunderbolts", price: 25000, rarity: "legendary", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Luck Blade", price: 25000, rarity: "legendary", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Sword of Answering", price: 25000, rarity: "legendary", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Holy Avenger", price: 25000, rarity: "legendary", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Ring of Djinni Summoning", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Invisibility", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Spell Turning", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Rod of Lordly Might", price: 25000, rarity: "legendary", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Vorpal Sword", price: 25000, rarity: "legendary", shops: ["firearms"], loot: ["space"], category: "weapon" },
      { name: "Belt of Cloud Giant Strength", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +2 Breastplate", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +3 Chain Mail", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +3 Chain Shirt", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Cloak of Invisibility", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Crystal Ball (Legendary)", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +1 Half Plate", price: 10000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Iron Flask", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +3 Leather", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +1 Plate", price: 10000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Robe of the Archmagi", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Rod of Resurrection", price: 25000, rarity: "legendary", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +1 Scale Mail", price: 10000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Scarab of Protection", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +2 Splint", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +2 Studded Leather", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Well of Many Worlds", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Armor, +2 Half Plate", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +2 Plate", price: 15000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +3 Studded Leather", price: 20000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +3 Breastplate", price: 20000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +3 Splint", price: 20000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +3 Half Plate", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor, +3 Plate", price: 30000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Apparatus of Kwalish", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Armor of Invulnerability", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Belt of Storm Giant Strength", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Cubic Gate", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Deck of Many Things", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Efreeti Chain", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Armor of Resistance (Half Plate)", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Horn of Valhalla (Iron)", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Instrument of the Bards (Ollamh Harp)", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Greater Absorption)", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Mastery)", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ioun Stone (Regeneration)", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Plate Armor of Etherealness", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Plate Armor of Resistance", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "armor" },
      { name: "Ring of Air Elemental Command", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Earth Elemental Command", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Fire Elemental Command", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Three Wishes", price: 50000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Ring of Water Elemental Command", price: 25000, rarity: "legendary", shops: ["cybernetics"], loot: ["space"], category: "wondrous" },
      { name: "Sphere of Annihilation", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Talisman of Pure Good", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Talisman of the Sphere", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Talisman of Ultimate Evil", price: 25000, rarity: "legendary", shops: ["general"], loot: ["space"], category: "wondrous" },
      { name: "Tome of the Stilled Tongue", price: 25000, rarity: "legendary", shops: ["pharmacist"], loot: ["space"], category: "wondrous" },

      // ==================== MUNDANE WEAPONS ====================
      { name: "Club", price: 0.1, rarity: "common", shops: ["firearms", "general"], loot: ["civilian"], category: "weapon" },
      { name: "Dagger", price: 2, rarity: "common", shops: ["firearms", "general"], loot: ["civilian", "guard"], category: "weapon" },
      { name: "Greatclub", price: 0.2, rarity: "common", shops: ["firearms"], loot: ["civilian"], category: "weapon" },
      { name: "Handaxe", price: 5, rarity: "common", shops: ["firearms", "general"], loot: ["civilian", "guard"], category: "weapon" },
      { name: "Javelin", price: 0.5, rarity: "common", shops: ["firearms"], loot: ["guard"], category: "weapon" },
      { name: "Light Hammer", price: 2, rarity: "common", shops: ["firearms", "general"], loot: ["civilian"], category: "weapon" },
      { name: "Mace", price: 5, rarity: "common", shops: ["firearms"], loot: ["guard"], category: "weapon" },
      { name: "Quarterstaff", price: 0.2, rarity: "common", shops: ["firearms", "general"], loot: ["civilian"], category: "weapon" },
      { name: "Sickle", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "weapon" },
      { name: "Spear", price: 1, rarity: "common", shops: ["firearms"], loot: ["guard"], category: "weapon" },
      { name: "Light Crossbow", price: 25, rarity: "common", shops: ["firearms"], loot: ["civilian", "guard"], category: "weapon" },
      { name: "Dart", price: 0.05, rarity: "common", shops: ["firearms"], loot: ["civilian"], category: "weapon" },
      { name: "Shortbow", price: 25, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Sling", price: 0.1, rarity: "common", shops: ["firearms", "general"], loot: ["civilian"], category: "weapon" },
      { name: "Battleaxe", price: 10, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Flail", price: 10, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Glaive", price: 20, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Greataxe", price: 30, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Greatsword", price: 50, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Halberd", price: 20, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Lance", price: 10, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Longsword", price: 15, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Maul", price: 10, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Morningstar", price: 15, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Pike", price: 5, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Rapier", price: 25, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Scimitar", price: 25, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Shortsword", price: 10, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Trident", price: 5, rarity: "common", shops: ["firearms"], loot: ["guard"], category: "weapon" },
      { name: "War Pick", price: 5, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Warhammer", price: 15, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Whip", price: 2, rarity: "common", shops: ["firearms"], loot: ["guard"], category: "weapon" },
      { name: "Blowgun", price: 10, rarity: "common", shops: ["firearms"], loot: ["guard"], category: "weapon" },
      { name: "Hand Crossbow", price: 75, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Heavy Crossbow", price: 50, rarity: "common", shops: ["firearms"], loot: ["guard", "military"], category: "weapon" },
      { name: "Longbow", price: 50, rarity: "common", shops: ["firearms"], loot: ["military"], category: "weapon" },
      { name: "Net", price: 1, rarity: "common", shops: ["firearms", "general"], loot: ["guard"], category: "weapon" },

      // ==================== MUNDANE ARMOR ====================
      { name: "Padded Armor", price: 5, rarity: "common", shops: ["cybernetics"], loot: ["civilian"], category: "armor" },
      { name: "Leather Armor", price: 10, rarity: "common", shops: ["cybernetics"], loot: ["civilian", "guard"], category: "armor" },
      { name: "Studded Leather Armor", price: 45, rarity: "common", shops: ["cybernetics"], loot: ["guard"], category: "armor" },
      { name: "Hide Armor", price: 10, rarity: "common", shops: ["cybernetics"], loot: ["civilian"], category: "armor" },
      { name: "Chain Shirt", price: 50, rarity: "common", shops: ["cybernetics"], loot: ["guard"], category: "armor" },
      { name: "Scale Mail", price: 50, rarity: "common", shops: ["cybernetics"], loot: ["guard", "military"], category: "armor" },
      { name: "Breastplate", price: 400, rarity: "uncommon", shops: ["cybernetics"], loot: ["military"], category: "armor" },
      { name: "Half Plate", price: 750, rarity: "uncommon", shops: ["cybernetics"], loot: ["military"], category: "armor" },
      { name: "Ring Mail", price: 30, rarity: "common", shops: ["cybernetics"], loot: ["guard"], category: "armor" },
      { name: "Chain Mail", price: 75, rarity: "common", shops: ["cybernetics"], loot: ["guard", "military"], category: "armor" },
      { name: "Splint Armor", price: 200, rarity: "uncommon", shops: ["cybernetics"], loot: ["military"], category: "armor" },
      { name: "Plate Armor", price: 1500, rarity: "rare", shops: ["cybernetics"], loot: ["military", "space"], category: "armor" },
      { name: "Shield", price: 10, rarity: "common", shops: ["cybernetics"], loot: ["guard", "military"], category: "armor" },

      // ==================== AMMUNITION ====================
      { name: "Arrows (20)", price: 1, rarity: "common", shops: ["firearms", "general"], loot: ["civilian", "guard", "military"], category: "ammo" },
      { name: "Blowgun Needles (50)", price: 1, rarity: "common", shops: ["firearms"], loot: ["guard"], category: "ammo" },
      { name: "Crossbow Bolts (20)", price: 1, rarity: "common", shops: ["firearms", "general"], loot: ["civilian", "guard", "military"], category: "ammo" },
      { name: "Sling Bullets (20)", price: 0.04, rarity: "common", shops: ["firearms", "general"], loot: ["civilian"], category: "ammo" },

      // ==================== ADVENTURING GEAR ====================
      { name: "Abacus", price: 2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Acid (vial)", price: 25, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military"], category: "consumable" },
      { name: "Alchemist's Fire (flask)", price: 50, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military"], category: "consumable" },
      { name: "Antitoxin (vial)", price: 50, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military"], category: "consumable" },
      { name: "Backpack", price: 2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Ball Bearings (bag of 1,000)", price: 1, rarity: "common", shops: ["general"], loot: ["guard"], category: "gear" },
      { name: "Barrel", price: 2, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Basket", price: 0.4, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Bedroll", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Bell", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Blanket", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Block and Tackle", price: 1, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Book", price: 25, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Bottle, glass", price: 2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Bucket", price: 0.05, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Caltrops (bag of 20)", price: 1, rarity: "common", shops: ["general"], loot: ["guard", "military"], category: "gear" },
      { name: "Candle", price: 0.01, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Case, Crossbow Bolt", price: 1, rarity: "common", shops: ["general", "firearms"], loot: ["guard"], category: "gear" },
      { name: "Case, Map or Scroll", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Chain (10 feet)", price: 5, rarity: "common", shops: ["general"], loot: ["guard"], category: "gear" },
      { name: "Chalk (1 piece)", price: 0.01, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Chest", price: 5, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Climber's Kit", price: 25, rarity: "common", shops: ["general"], loot: ["guard", "military"], category: "gear" },
      { name: "Clothes, Common", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Clothes, Costume", price: 5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Clothes, Fine", price: 15, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Clothes, Traveler's", price: 2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Component Pouch", price: 25, rarity: "common", shops: ["general", "pharmacist"], loot: ["guard"], category: "gear" },
      { name: "Crowbar", price: 2, rarity: "common", shops: ["general"], loot: ["civilian", "guard"], category: "gear" },
      { name: "Fishing Tackle", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Flask or Tankard", price: 0.02, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Grappling Hook", price: 2, rarity: "common", shops: ["general"], loot: ["guard", "military"], category: "gear" },
      { name: "Hammer", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Hammer, Sledge", price: 2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Healer's Kit", price: 5, rarity: "common", shops: ["general", "pharmacist"], loot: ["civilian", "guard", "military"], category: "gear" },
      { name: "Holy Water (flask)", price: 25, rarity: "common", shops: ["general", "pharmacist"], loot: ["guard"], category: "consumable" },
      { name: "Hourglass", price: 25, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Hunting Trap", price: 5, rarity: "common", shops: ["general"], loot: ["guard"], category: "gear" },
      { name: "Ink (1 ounce bottle)", price: 10, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Ink Pen", price: 0.02, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Jug or Pitcher", price: 0.02, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Ladder (10-foot)", price: 0.1, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Lamp", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Lantern, Bullseye", price: 10, rarity: "common", shops: ["general"], loot: ["guard"], category: "gear" },
      { name: "Lantern, Hooded", price: 5, rarity: "common", shops: ["general"], loot: ["civilian", "guard"], category: "gear" },
      { name: "Lock", price: 10, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Magnifying Glass", price: 100, rarity: "uncommon", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Manacles", price: 2, rarity: "common", shops: ["general"], loot: ["guard", "military"], category: "gear" },
      { name: "Mess Kit", price: 0.2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Mirror, Steel", price: 5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Oil (flask)", price: 0.1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "consumable" },
      { name: "Paper (one sheet)", price: 0.2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Parchment (one sheet)", price: 0.1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Perfume (vial)", price: 5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Pick, Miner's", price: 2, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Piton", price: 0.05, rarity: "common", shops: ["general"], loot: ["guard"], category: "gear" },
      { name: "Poison, Basic (vial)", price: 100, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military"], category: "consumable" },
      { name: "Pole (10-foot)", price: 0.05, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Pot, Iron", price: 2, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Pouch", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Quiver", price: 1, rarity: "common", shops: ["general", "firearms"], loot: ["guard"], category: "gear" },
      { name: "Ram, Portable", price: 4, rarity: "common", shops: ["general"], loot: ["guard", "military"], category: "gear" },
      { name: "Rations (1 day)", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian", "guard"], category: "consumable" },
      { name: "Robes", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Rope, Hempen (50 feet)", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Rope, Silk (50 feet)", price: 10, rarity: "common", shops: ["general"], loot: ["guard", "military"], category: "gear" },
      { name: "Sack", price: 0.01, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Scale, Merchant's", price: 5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Sealing Wax", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Shovel", price: 2, rarity: "common", shops: ["general"], loot: [], category: "gear" },
      { name: "Signal Whistle", price: 0.05, rarity: "common", shops: ["general"], loot: ["civilian", "guard"], category: "gear" },
      { name: "Signet Ring", price: 5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Soap", price: 0.02, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Spellbook", price: 50, rarity: "common", shops: ["general", "pharmacist"], loot: [], category: "gear" },
      { name: "Spikes, Iron (10)", price: 1, rarity: "common", shops: ["general"], loot: ["guard"], category: "gear" },
      { name: "Spyglass", price: 1000, rarity: "rare", shops: ["general"], loot: ["military", "space"], category: "gear" },
      { name: "Tent, Two-Person", price: 2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Tinderbox", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Torch", price: 0.01, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Vial", price: 1, rarity: "common", shops: ["general", "pharmacist"], loot: ["civilian"], category: "gear" },
      { name: "Waterskin", price: 0.2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },
      { name: "Whetstone", price: 0.01, rarity: "common", shops: ["general"], loot: ["civilian"], category: "gear" },

      // ==================== TOOLS ====================
      { name: "Alchemist's Supplies", price: 50, rarity: "common", shops: ["general", "pharmacist"], loot: [], category: "tools" },
      { name: "Brewer's Supplies", price: 20, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Calligrapher's Supplies", price: 10, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Carpenter's Tools", price: 8, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Cartographer's Tools", price: 15, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Cobbler's Tools", price: 5, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Cook's Utensils", price: 1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "tools" },
      { name: "Glassblower's Tools", price: 30, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Jeweler's Tools", price: 25, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Leatherworker's Tools", price: 5, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Mason's Tools", price: 10, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Painter's Supplies", price: 10, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Potter's Tools", price: 10, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Smith's Tools", price: 20, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Tinker's Tools", price: 50, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Weaver's Tools", price: 1, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Woodcarver's Tools", price: 1, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Dice Set", price: 0.1, rarity: "common", shops: ["general"], loot: ["civilian"], category: "tools" },
      { name: "Playing Card Set", price: 0.5, rarity: "common", shops: ["general"], loot: ["civilian"], category: "tools" },
      { name: "Herbalism Kit", price: 5, rarity: "common", shops: ["general", "pharmacist"], loot: [], category: "tools" },
      { name: "Bagpipes", price: 30, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Drum", price: 6, rarity: "common", shops: ["general"], loot: ["civilian"], category: "tools" },
      { name: "Flute", price: 2, rarity: "common", shops: ["general"], loot: ["civilian"], category: "tools" },
      { name: "Lute", price: 35, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Lyre", price: 30, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Horn", price: 3, rarity: "common", shops: ["general"], loot: ["civilian"], category: "tools" },
      { name: "Navigator's Tools", price: 25, rarity: "common", shops: ["general"], loot: [], category: "tools" },
      { name: "Poisoner's Kit", price: 50, rarity: "common", shops: ["pharmacist"], loot: ["guard", "military"], category: "tools" },
      { name: "Thieves' Tools", price: 25, rarity: "common", shops: ["general"], loot: ["guard"], category: "tools" },
      { name: "Disguise Kit", price: 25, rarity: "common", shops: ["general"], loot: ["guard", "military"], category: "tools" },
      { name: "Forgery Kit", price: 15, rarity: "common", shops: ["general"], loot: ["guard"], category: "tools" },

      // ==================== GEMS (Jackpot Only) ====================
      { name: "Azurite (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Banded Agate (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Blue Quartz (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Eye Agate (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Hematite (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Lapis Lazuli (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Malachite (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Moss Agate (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Obsidian (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Rhodochrosite (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Tiger Eye (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Turquoise (10 gp)", price: 10, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Bloodstone (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Carnelian (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Chalcedony (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Chrysoprase (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Citrine (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Jasper (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Moonstone (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Onyx (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Quartz (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Sardonyx (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Star Rose Quartz (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Zircon (50 gp)", price: 50, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Amber (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Amethyst (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Chrysoberyl (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Coral (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Garnet (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Jade (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Jet (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Pearl (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Spinel (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Tourmaline (100 gp)", price: 100, rarity: "rare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Alexandrite (500 gp)", price: 500, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Aquamarine (500 gp)", price: 500, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Black Pearl (500 gp)", price: 500, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Blue Spinel (500 gp)", price: 500, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Peridot (500 gp)", price: 500, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Topaz (500 gp)", price: 500, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Black Opal (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Blue Sapphire (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Emerald (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Fire Opal (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Opal (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Star Ruby (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Star Sapphire (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Yellow Sapphire (1,000 gp)", price: 1000, rarity: "veryRare", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Black Sapphire (5,000 gp)", price: 5000, rarity: "legendary", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Diamond (5,000 gp)", price: 5000, rarity: "legendary", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Jacinth (5,000 gp)", price: 5000, rarity: "legendary", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },
      { name: "Ruby (5,000 gp)", price: 5000, rarity: "legendary", shops: [], loot: ["space"], category: "gem", jackpotOnly: true },

      // ==================== ART OBJECTS (Jackpot Only) ====================
      { name: "Silver Ewer (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Carved Bone Statuette (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Small Gold Bracelet (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Cloth-of-Gold Vestments (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Black Velvet Mask (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Copper Chalice with Silver Filigree (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Pair of Engraved Bone Dice (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Small Mirror in Painted Frame (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Embroidered Silk Handkerchief (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Locket with Portrait (25 gp)", price: 25, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Ring with Bloodstones (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Carved Ivory Statuette (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Large Gold Bracelet (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Silver Necklace with Gemstone (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Bronze Crown (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Silk Robe with Gold Embroidery (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Large Well-Made Tapestry (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Brass Mug with Jade Inlay (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Box of Turquoise Figurines (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Bird Cage with Electrum (250 gp)", price: 250, rarity: "rare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Silver Chalice with Moonstones (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Silver-Plated Longsword with Jet (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Carved Harp of Exotic Wood (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Small Gold Idol (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Dragon Comb (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Leaf Bottle Stopper (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Ceremonial Electrum Dagger (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Silver and Gold Brooch (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Obsidian Statuette with Gold (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Painted Gold War Mask (750 gp)", price: 750, rarity: "veryRare", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Fine Gold Chain with Fire Opal (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Old Masterpiece Painting (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Embroidered Mantle with Moonstones (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Platinum Bracelet with Sapphire (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Embroidered Glove with Jewel Chips (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Jeweled Anklet (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Music Box (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Circlet with Aquamarines (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Eye Patch with Sapphire (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Pink Pearl Necklace (2,500 gp)", price: 2500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Jeweled Gold Crown (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Jeweled Platinum Ring (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Statuette with Rubies (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Cup with Emeralds (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Gold Jewelry Box with Platinum (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Painted Gold Child's Sarcophagus (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Jade Game Board with Gold Pieces (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
      { name: "Bejeweled Ivory Drinking Horn (7,500 gp)", price: 7500, rarity: "legendary", shops: [], loot: ["space"], category: "art", jackpotOnly: true },
    ];